questions = {
    1: {"The sun is a star.": "True"},
    2: {"Water boils at 100°C (212°F) at sea level.": "True"},
    3: {"Sharks are mammals.": "False"},
    4: {"Mount Everest is the tallest mountain in the world.": "True"},
    5: {"An octopus has five hearts.": "False"},
    6: {"Bananas grow on trees.": "False"},
    7: {"The capital of Australia is Sydney.": "False"},
    8: {"Humans have four lungs.": "False"},
    9: {"There are 365 days in a year.": "True"},
    10: {"Goldfish only have a memory of three seconds.": "False"},
    11: {"The Great Wall of China is visible from space.": "False"},
    12: {"An adult human body has 206 bones.": "True"},
    13: {"Lightning never strikes the same place twice.": "False"},
    14: {"Venus is the hottest planet in our solar system.": "True"},
    15: {"The Amazon Rainforest is the largest rainforest in the world.": "True"},
    16: {"Bats are blind.": "False"},
    17: {"A crocodile cannot stick its tongue out.": "True"},
    18: {"Sound travels faster in air than in water.": "False"},
    19: {"The human heart has four chambers.": "True"},
    20: {"An ostrich's eye is bigger than its brain.": "True"},
    21: {"Cows can sleep standing up.": "True"},
    22: {"The Statue of Liberty was a gift from France.": "True"},
    23: {"Diamonds are made of compressed coal.": "False"},
    24: {"The Atlantic Ocean is the largest ocean on Earth.": "False"},
    25: {"Elephants are the only animals that can't jump.": "True"},
    26: {"A day on Mars is longer than a day on Earth.": "True"},
    27: {"Penguins can fly.": "False"},
    28: {"Water is made up of hydrogen and oxygen.": "True"},
    29: {"Humans share about 50% of their DNA with bananas.": "True"},
    30: {"There are seven continents on Earth.": "True"}
}
