people = [
    {"name": "Shawn Mendes", "follower_count": "75", "description": "Musician", "country": "Canada"},
    {"name": "Cristiano Ronaldo", "follower_count": "615", "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": "490", "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": "429", "description": "Musician", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": "399", "description": "Actor", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": "380", "description": "Musician", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": "364", "description": "Media Personality", "country": "USA"},
    {"name": "Beyoncé", "follower_count": "319", "description": "Musician", "country": "USA"},
    {"name": "Khloé Kardashian", "follower_count": "310", "description": "Media Personality", "country": "USA"},
    {"name": "Nike", "follower_count": "307", "description": "Brand", "country": "USA"},
    {"name": "Kendall Jenner", "follower_count": "293", "description": "Model", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": "291", "description": "Musician", "country": "Canada"},
    {"name": "National Geographic", "follower_count": "283", "description": "Media", "country": "USA"},
    {"name": "Taylor Swift", "follower_count": "275", "description": "Musician", "country": "USA"},
    {"name": "Jennifer Lopez", "follower_count": "253", "description": "Musician", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": "267", "description": "Cricketer", "country": "India"},
    {"name": "Nicki Minaj", "follower_count": "229", "description": "Musician", "country": "USA"},
    {"name": "Kourtney Kardashian", "follower_count": "223", "description": "Media Personality", "country": "USA"},
    {"name": "Zendaya", "follower_count": "190", "description": "Actress", "country": "USA"},
    {"name": "LeBron James", "follower_count": "159", "description": "Basketball Player", "country": "USA"},
    {"name": "Drake", "follower_count": "143", "description": "Musician", "country": "Canada"},
    {"name": "Billie Eilish", "follower_count": "112", "description": "Musician", "country": "USA"},
    {"name": "Emma Watson", "follower_count": "106", "description": "Actress", "country": "UK"},
    {"name": "Priyanka Chopra", "follower_count": "91", "description": "Actress", "country": "India"},
    {"name": "Robert Downey Jr.", "follower_count": "95", "description": "Actor", "country": "USA"},
    {"name": "Chris Hemsworth", "follower_count": "80", "description": "Actor", "country": "Australia"},
    {"name": "Shah Rukh Khan", "follower_count": "82", "description": "Actor", "country": "India"},
    {"name": "Will Smith", "follower_count": "78", "description": "Actor", "country": "USA"},
    {"name": "Kevin Hart", "follower_count": "66", "description": "Comedian", "country": "USA"},
    {"name": "David Beckham", "follower_count": "88", "description": "Footballer", "country": "UK"}
]
